document:
  analyzer:
    version: 0.01

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true