version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - /home/musashi/Documents/proyectos/dbs/postgres-volume:/postgres-volume
      - pg_data:/var/lib/postgresql/data/
volumes:
  pg_data: